version: "3.9"
services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/crimwatch
      - JWT_SECRET=sua_chave_super_secreta
    depends_on:
      - mongo
    volumes:
      - .:/app
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
