# Generated by Django 5.2.1 on 2025-05-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('tipoCrime', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
    ]
