# Generated by Django 5.2.1 on 2025-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='campo1',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='campo2',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
    ]
